orn_app_homepage:
    path:     /
    defaults: { _controller: ORNAppBundle:Default:index }

orn_app_aboutpage:
    path:     /about
    defaults: { _controller: ORNAppBundle:Default:about }

orn_app_contactpage:
    path:     /contact
    defaults: { _controller: ORNAppBundle:Default:contact }