orncp_homepage:
    path:     /
    defaults: { _controller: ORNCPBundle:Default:index }

orncp_profilepage:
    path:     /profile
    defaults: { _controller: ORNCPBundle:Default:profile }

index:
    path:     /profile
    defaults: { _controller: ORNCPBundle:Profile:index }
